/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.yalantis.phoenix;

public final class R {
	public static final class attr {
		public static final int type = 0x7f010016;
	}
	public static final class dimen {
		public static final int activity_horizontal_margin = 0x7f070011;
		public static final int activity_vertical_margin = 0x7f070012;
	}
	public static final class drawable {
		public static final int buildings = 0x7f02001b;
		public static final int ic_launcher = 0x7f020087;
		public static final int sky = 0x7f02010f;
		public static final int sun = 0x7f02011d;
	}
	public static final class id {
		public static final int sun = 0x7f0a0008;
	}
	public static final class layout {
		public static final int activity_main = 0x7f030007;
	}
	public static final class menu {
		public static final int main = 0x7f0e0000;
	}
	public static final class string {
		public static final int action_settings = 0x7f080004;
		public static final int app_name = 0x7f080003;
		public static final int hello_world = 0x7f080005;
	}
	public static final class styleable {
		public static final int[] RefreshView = { 0x7f010016 };
		public static final int RefreshView_type = 0;
	}
}
